"""Render every ```mermaid block in docs/ARCHITECTURE.md and docs/RULES.md to SVG.

    uv run python scripts/render_diagrams.py            # write docs/diagrams/*.mmd and *.svg
    uv run python scripts/render_diagrams.py --png      # also PNGs (not committed; for a quick look)
    uv run python scripts/render_diagrams.py --check    # render to a temp dir only: a syntax check

Each block is written to `docs/diagrams/<doc>-<nn>-<heading-slug>.mmd`, named from the
nearest heading above it, and rendered with mermaid-cli in Docker
(`minlag/mermaid-cli`, no node on the box). A block that fails to render fails the
script, so this doubles as the Mermaid syntax check the Markdown sources otherwise lack.
The Markdown keeps the inline blocks (Obsidian and GitHub render those); the SVGs are for
the paper, for viewers without Mermaid, and for `docs/diagrams/README.md`, which this
script writes as an index. Run it after editing either source; `docs/RULES.md` is itself
generated (`scripts/rules_catalogue.py`), so regenerate that first.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "diagrams"
SOURCES = [DOCS / "ARCHITECTURE.md", DOCS / "RULES.md"]
IMAGE = "minlag/mermaid-cli"
CONFIG = {"theme": "neutral", "flowchart": {"htmlLabels": True, "curve": "basis"}, "securityLevel": "loose"}

_FENCE = re.compile(r"^```mermaid\s*$")
_HEADING = re.compile(r"^(#+)\s+(.*)$")


def _slug(s: str) -> str:
    s = re.sub(r"`|\*", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:48]


def extract(md: Path) -> list[tuple[str, str]]:
    """(name, mermaid source) for every block, named from the nearest heading above."""
    out: list[tuple[str, str]] = []
    heading = md.stem.lower()
    buf: list[str] | None = None
    for line in md.read_text(encoding="utf-8").splitlines():
        if buf is None:
            m = _HEADING.match(line)
            if m:
                heading = m.group(2)
            elif _FENCE.match(line):
                buf = []
            continue
        if line.strip() == "```":
            out.append((f"{md.stem.lower()}-{len(out) + 1:02d}-{_slug(heading)}", "\n".join(buf) + "\n"))
            buf = None
        else:
            buf.append(line)
    return out


def render(mmd: Path, svg: Path, *, png: bool) -> None:
    """mermaid-cli in Docker; the work dir is bind-mounted at /data."""
    work = mmd.parent
    cfg = work / ".mermaid-config.json"
    cfg.write_text(__import__("json").dumps(CONFIG), encoding="utf-8")
    base = ["docker", "run", "--rm", "-u", f"{os.getuid()}:{os.getgid()}", "-v", f"{work}:/data", IMAGE,
            "-i", f"/data/{mmd.name}", "-c", f"/data/{cfg.name}", "-b", "transparent"]
    subprocess.run(base + ["-o", f"/data/{svg.name}"], check=True)
    if png:
        subprocess.run(base + ["-o", f"/data/{svg.with_suffix('.png').name}", "-s", "2"], check=True)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--png", action="store_true", help="also write PNGs at 2x (gitignored)")
    ap.add_argument("--check", action="store_true", help="render into a temporary directory only")
    args = ap.parse_args(argv)
    if shutil.which("docker") is None:
        print("docker is required (image minlag/mermaid-cli)", file=sys.stderr)
        return 2
    target = Path(tempfile.mkdtemp(prefix="mermaid-")) if args.check else OUT
    target.mkdir(parents=True, exist_ok=True)
    blocks = [(src, name, text) for src in SOURCES for name, text in extract(src)]
    failed: list[str] = []
    index: list[str] = ["# Rendered diagrams", "",
                        "Generated by `scripts/render_diagrams.py` from the ```mermaid blocks of `docs/ARCHITECTURE.md`",
                        "and `docs/RULES.md`; do not edit the `.mmd` or `.svg` files by hand. Rerun after editing either",
                        "source (`docs/RULES.md` first via `scripts/rules_catalogue.py`).", ""]
    for src, name, text in blocks:
        mmd, svg = target / f"{name}.mmd", target / f"{name}.svg"
        mmd.write_text(text, encoding="utf-8")
        try:
            render(mmd, svg, png=args.png)
            print(f"ok   {name}.svg")
            index.append(f"- `{name}.svg` ({src.name}) ![{name}]({name}.svg)")
        except subprocess.CalledProcessError:
            failed.append(name)
            print(f"FAIL {name}", file=sys.stderr)
    if not args.check:
        (target / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
        (target / ".mermaid-config.json").unlink(missing_ok=True)
    else:
        shutil.rmtree(target, ignore_errors=True)
    print(f"{len(blocks) - len(failed)} of {len(blocks)} diagrams rendered" + (f"; failed: {failed}" if failed else ""))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
